# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c11701f5d96595cae0cfe699199501fbc4d5f70900c3bde6e1eef494f8ee7a7f619062a9057af2e629d69c026652ea5815f78dc97b86a287236cdde1f4f058

test:
  secret_key_base: e17b3ec19e2829879b5d214d47330ba61b598b66e13353edace1998aff7ed5368b55b648bbe009066e44012e40a3822f3ec37da8d2cff2645e8f86d7fe073896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
